[package]
name = "instant-distance-py"
version = "0.3.5"
edition = "2021"
rust-version = "1.58"
license = "MIT OR Apache-2.0"
workspace = ".."
description = "Fast minimal implementation of HNSW maps for approximate nearest neighbors searches"
homepage = "https://github.com/InstantDomain/instant-distance"
repository = "https://github.com/InstantDomain/instant-distance"
readme = "../README.md"

[lib]
name = "instant_distance_py"
crate-type = ["cdylib", "lib"]

[package.metadata.maturin]
name = "instant_distance"

[dependencies]
aligned-vec = { version = "0.5.0", features = ["serde"] }
bincode = "1.3.1"
instant-distance = { version = "0.6", path = "../instant-distance", features = [
    "with-serde",
] }
pyo3 = { version = "0.18.0", features = ["extension-module"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
anyhow = "1.0.75"
bencher = "0.1.5"
structopt = "0.3.24"
rand = { version = "0.8", features = ["small_rng"] }

[[bench]]
name = "all"
harness = false
